name: 'Chromatic'

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    if: (!github.event.pull_request.draft && github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
