name: IPFS Preview Deploy
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ipfs-preview-build:
    runs-on: ubuntu-latest
    steps:
      - name: Inject slug variables
        uses: rlespinasse/github-slug-action@v4.4.0
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: true
          cache: 'yarn'
      - name: Start Deployment
        uses: bobheadxi/deployments@v1.3.0
        id: deployment
        with:
          step: start
          token: ${{secrets.GITHUB_TOKEN}}
          env: ${{env.GITHUB_HEAD_REF_SLUG_URL || env.GITHUB_REF_SLUG_URL}}
          ref: ${{github.head_ref}}
      - name: Install dependencies
        run: yarn install --frozen-lockfile --cache-folder $(yarn cache dir)

      - name: Build
        run: yarn ipfs-build
      - name: Deploy to IPFS
        uses: web3-storage/add-to-web3@v2
        id: web3
        with:
          web3_token: ${{secrets.WEB3_STORAGE_TOKEN}}
          path_to_add: 'build'
      - name: Update Deployment Status
        uses: bobheadxi/deployments@v1.3.0
        if: always()
        with:
          step: finish
          token: ${{secrets.GITHUB_TOKEN}}
          status: ${{job.status}}
          deployment_id: ${{steps.deployment.outputs.deployment_id}}
          env_url: 'https://${{steps.web3.outputs.cid}}.ipfs.dweb.link'
